// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod tobmapgraph {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_TRAVEL_MODE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_TRAVEL_MODE: i8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_TRAVEL_MODE: [TravelMode; 4] = [
  TravelMode::Car,
  TravelMode::Bike,
  TravelMode::Walk,
  TravelMode::Transit,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct TravelMode(pub i8);
#[allow(non_upper_case_globals)]
impl TravelMode {
  pub const Car: Self = Self(0);
  pub const Bike: Self = Self(1);
  pub const Walk: Self = Self(2);
  pub const Transit: Self = Self(3);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Car,
    Self::Bike,
    Self::Walk,
    Self::Transit,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Car => Some("Car"),
      Self::Bike => Some("Bike"),
      Self::Walk => Some("Walk"),
      Self::Transit => Some("Transit"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for TravelMode {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for TravelMode {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for TravelMode {
    type Output = TravelMode;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for TravelMode {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for TravelMode {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for TravelMode {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ROAD_INTERACTION: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ROAD_INTERACTION: i8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ROAD_INTERACTION: [RoadInteraction; 4] = [
  RoadInteraction::None,
  RoadInteraction::Yield,
  RoadInteraction::StopSign,
  RoadInteraction::TrafficLight,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct RoadInteraction(pub i8);
#[allow(non_upper_case_globals)]
impl RoadInteraction {
  pub const None: Self = Self(0);
  pub const Yield: Self = Self(1);
  pub const StopSign: Self = Self(2);
  pub const TrafficLight: Self = Self(3);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::Yield,
    Self::StopSign,
    Self::TrafficLight,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::Yield => Some("Yield"),
      Self::StopSign => Some("StopSign"),
      Self::TrafficLight => Some("TrafficLight"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for RoadInteraction {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for RoadInteraction {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for RoadInteraction {
    type Output = RoadInteraction;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for RoadInteraction {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for RoadInteraction {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for RoadInteraction {}
// struct Interactions, aligned to 1
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Interactions(pub [u8; 2]);
impl Default for Interactions { 
  fn default() -> Self { 
    Self([0; 2])
  }
}
impl core::fmt::Debug for Interactions {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Interactions")
      .field("incoming", &self.incoming())
      .field("outgoing", &self.outgoing())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Interactions {}
impl<'a> flatbuffers::Follow<'a> for Interactions {
  type Inner = &'a Interactions;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Interactions>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Interactions {
  type Inner = &'a Interactions;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Interactions>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Interactions {
    type Output = Interactions;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Interactions as *const u8, <Self as flatbuffers::Push>::size());
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(1)
    }
}

impl<'a> flatbuffers::Verifiable for Interactions {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Interactions {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    incoming: RoadInteraction,
    outgoing: RoadInteraction,
  ) -> Self {
    let mut s = Self([0; 2]);
    s.set_incoming(incoming);
    s.set_outgoing(outgoing);
    s
  }

  pub fn incoming(&self) -> RoadInteraction {
    let mut mem = core::mem::MaybeUninit::<<RoadInteraction as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<RoadInteraction as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_incoming(&mut self, x: RoadInteraction) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<RoadInteraction as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn outgoing(&self) -> RoadInteraction {
    let mut mem = core::mem::MaybeUninit::<<RoadInteraction as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[1..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<RoadInteraction as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_outgoing(&mut self, x: RoadInteraction) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[1..].as_mut_ptr(),
        core::mem::size_of::<<RoadInteraction as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum NodeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Node<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Node<'a> {
  type Inner = Node<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Node<'a> {
  pub const VT_CELL_ID: flatbuffers::VOffsetT = 4;
  pub const VT_EDGES: flatbuffers::VOffsetT = 6;
  pub const VT_INTERACTIONS: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Node { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NodeArgs<'args>
  ) -> flatbuffers::WIPOffset<Node<'bldr>> {
    let mut builder = NodeBuilder::new(_fbb);
    builder.add_cell_id(args.cell_id);
    if let Some(x) = args.interactions { builder.add_interactions(x); }
    if let Some(x) = args.edges { builder.add_edges(x); }
    builder.finish()
  }


  #[inline]
  pub fn cell_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Node::VT_CELL_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn edges(&self) -> Option<flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u64>>>(Node::VT_EDGES, None)}
  }
  #[inline]
  pub fn interactions(&self) -> Option<flatbuffers::Vector<'a, Interactions>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Interactions>>>(Node::VT_INTERACTIONS, None)}
  }
}

impl flatbuffers::Verifiable for Node<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("cell_id", Self::VT_CELL_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u64>>>("edges", Self::VT_EDGES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Interactions>>>("interactions", Self::VT_INTERACTIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct NodeArgs<'a> {
    pub cell_id: u64,
    pub edges: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u64>>>,
    pub interactions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Interactions>>>,
}
impl<'a> Default for NodeArgs<'a> {
  #[inline]
  fn default() -> Self {
    NodeArgs {
      cell_id: 0,
      edges: None,
      interactions: None,
    }
  }
}

pub struct NodeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NodeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_cell_id(&mut self, cell_id: u64) {
    self.fbb_.push_slot::<u64>(Node::VT_CELL_ID, cell_id, 0);
  }
  #[inline]
  pub fn add_edges(&mut self, edges: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Node::VT_EDGES, edges);
  }
  #[inline]
  pub fn add_interactions(&mut self, interactions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Interactions>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Node::VT_INTERACTIONS, interactions);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NodeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NodeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Node<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Node<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Node");
      ds.field("cell_id", &self.cell_id());
      ds.field("edges", &self.edges());
      ds.field("interactions", &self.interactions());
      ds.finish()
  }
}
pub enum EdgeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Edge<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Edge<'a> {
  type Inner = Edge<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Edge<'a> {
  pub const VT_CELL_ID: flatbuffers::VOffsetT = 4;
  pub const VT_POINT_1_NODE_IDX: flatbuffers::VOffsetT = 6;
  pub const VT_POINT_2_NODE_IDX: flatbuffers::VOffsetT = 8;
  pub const VT_BACKWARDS_ALLOWED: flatbuffers::VOffsetT = 10;
  pub const VT_TRAVEL_COSTS: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Edge { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EdgeArgs<'args>
  ) -> flatbuffers::WIPOffset<Edge<'bldr>> {
    let mut builder = EdgeBuilder::new(_fbb);
    builder.add_point_2_node_idx(args.point_2_node_idx);
    builder.add_point_1_node_idx(args.point_1_node_idx);
    builder.add_cell_id(args.cell_id);
    if let Some(x) = args.travel_costs { builder.add_travel_costs(x); }
    builder.add_backwards_allowed(args.backwards_allowed);
    builder.finish()
  }


  #[inline]
  pub fn cell_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Edge::VT_CELL_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn point_1_node_idx(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Edge::VT_POINT_1_NODE_IDX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn point_2_node_idx(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Edge::VT_POINT_2_NODE_IDX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn backwards_allowed(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Edge::VT_BACKWARDS_ALLOWED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn travel_costs(&self) -> Option<flatbuffers::Vector<'a, f32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, f32>>>(Edge::VT_TRAVEL_COSTS, None)}
  }
}

impl flatbuffers::Verifiable for Edge<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("cell_id", Self::VT_CELL_ID, false)?
     .visit_field::<u64>("point_1_node_idx", Self::VT_POINT_1_NODE_IDX, false)?
     .visit_field::<u64>("point_2_node_idx", Self::VT_POINT_2_NODE_IDX, false)?
     .visit_field::<bool>("backwards_allowed", Self::VT_BACKWARDS_ALLOWED, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, f32>>>("travel_costs", Self::VT_TRAVEL_COSTS, false)?
     .finish();
    Ok(())
  }
}
pub struct EdgeArgs<'a> {
    pub cell_id: u64,
    pub point_1_node_idx: u64,
    pub point_2_node_idx: u64,
    pub backwards_allowed: bool,
    pub travel_costs: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, f32>>>,
}
impl<'a> Default for EdgeArgs<'a> {
  #[inline]
  fn default() -> Self {
    EdgeArgs {
      cell_id: 0,
      point_1_node_idx: 0,
      point_2_node_idx: 0,
      backwards_allowed: false,
      travel_costs: None,
    }
  }
}

pub struct EdgeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EdgeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_cell_id(&mut self, cell_id: u64) {
    self.fbb_.push_slot::<u64>(Edge::VT_CELL_ID, cell_id, 0);
  }
  #[inline]
  pub fn add_point_1_node_idx(&mut self, point_1_node_idx: u64) {
    self.fbb_.push_slot::<u64>(Edge::VT_POINT_1_NODE_IDX, point_1_node_idx, 0);
  }
  #[inline]
  pub fn add_point_2_node_idx(&mut self, point_2_node_idx: u64) {
    self.fbb_.push_slot::<u64>(Edge::VT_POINT_2_NODE_IDX, point_2_node_idx, 0);
  }
  #[inline]
  pub fn add_backwards_allowed(&mut self, backwards_allowed: bool) {
    self.fbb_.push_slot::<bool>(Edge::VT_BACKWARDS_ALLOWED, backwards_allowed, false);
  }
  #[inline]
  pub fn add_travel_costs(&mut self, travel_costs: flatbuffers::WIPOffset<flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Edge::VT_TRAVEL_COSTS, travel_costs);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EdgeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EdgeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Edge<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Edge<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Edge");
      ds.field("cell_id", &self.cell_id());
      ds.field("point_1_node_idx", &self.point_1_node_idx());
      ds.field("point_2_node_idx", &self.point_2_node_idx());
      ds.field("backwards_allowed", &self.backwards_allowed());
      ds.field("travel_costs", &self.travel_costs());
      ds.finish()
  }
}
pub enum GraphBlobOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GraphBlob<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GraphBlob<'a> {
  type Inner = GraphBlob<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> GraphBlob<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_EDGES: flatbuffers::VOffsetT = 6;
  pub const VT_NODES: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GraphBlob { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GraphBlobArgs<'args>
  ) -> flatbuffers::WIPOffset<GraphBlob<'bldr>> {
    let mut builder = GraphBlobBuilder::new(_fbb);
    if let Some(x) = args.nodes { builder.add_nodes(x); }
    if let Some(x) = args.edges { builder.add_edges(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GraphBlob::VT_NAME, None)}
  }
  #[inline]
  pub fn edges(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Edge<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Edge>>>>(GraphBlob::VT_EDGES, None)}
  }
  #[inline]
  pub fn nodes(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Node<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Node>>>>(GraphBlob::VT_NODES, None)}
  }
}

impl flatbuffers::Verifiable for GraphBlob<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Edge>>>>("edges", Self::VT_EDGES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Node>>>>("nodes", Self::VT_NODES, false)?
     .finish();
    Ok(())
  }
}
pub struct GraphBlobArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub edges: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Edge<'a>>>>>,
    pub nodes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Node<'a>>>>>,
}
impl<'a> Default for GraphBlobArgs<'a> {
  #[inline]
  fn default() -> Self {
    GraphBlobArgs {
      name: None,
      edges: None,
      nodes: None,
    }
  }
}

pub struct GraphBlobBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> GraphBlobBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphBlob::VT_NAME, name);
  }
  #[inline]
  pub fn add_edges(&mut self, edges: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Edge<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphBlob::VT_EDGES, edges);
  }
  #[inline]
  pub fn add_nodes(&mut self, nodes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Node<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GraphBlob::VT_NODES, nodes);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> GraphBlobBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GraphBlobBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GraphBlob<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GraphBlob<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GraphBlob");
      ds.field("name", &self.name());
      ds.field("edges", &self.edges());
      ds.field("nodes", &self.nodes());
      ds.finish()
  }
}
}  // pub mod tobmapgraph

