// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod tobmapsnap {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum SnapBucketOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SnapBucket<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SnapBucket<'a> {
  type Inner = SnapBucket<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SnapBucket<'a> {
  pub const VT_CELL_ID: flatbuffers::VOffsetT = 4;
  pub const VT_EDGE_CELL_IDS: flatbuffers::VOffsetT = 6;
  pub const VT_EDGE_INDEXES: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SnapBucket { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SnapBucketArgs<'args>
  ) -> flatbuffers::WIPOffset<SnapBucket<'bldr>> {
    let mut builder = SnapBucketBuilder::new(_fbb);
    builder.add_cell_id(args.cell_id);
    if let Some(x) = args.edge_indexes { builder.add_edge_indexes(x); }
    if let Some(x) = args.edge_cell_ids { builder.add_edge_cell_ids(x); }
    builder.finish()
  }


  #[inline]
  pub fn cell_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SnapBucket::VT_CELL_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn edge_cell_ids(&self) -> Option<flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u64>>>(SnapBucket::VT_EDGE_CELL_IDS, None)}
  }
  #[inline]
  pub fn edge_indexes(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(SnapBucket::VT_EDGE_INDEXES, None)}
  }
}

impl flatbuffers::Verifiable for SnapBucket<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("cell_id", Self::VT_CELL_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u64>>>("edge_cell_ids", Self::VT_EDGE_CELL_IDS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("edge_indexes", Self::VT_EDGE_INDEXES, false)?
     .finish();
    Ok(())
  }
}
pub struct SnapBucketArgs<'a> {
    pub cell_id: u64,
    pub edge_cell_ids: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u64>>>,
    pub edge_indexes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for SnapBucketArgs<'a> {
  #[inline]
  fn default() -> Self {
    SnapBucketArgs {
      cell_id: 0,
      edge_cell_ids: None,
      edge_indexes: None,
    }
  }
}

pub struct SnapBucketBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SnapBucketBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_cell_id(&mut self, cell_id: u64) {
    self.fbb_.push_slot::<u64>(SnapBucket::VT_CELL_ID, cell_id, 0);
  }
  #[inline]
  pub fn add_edge_cell_ids(&mut self, edge_cell_ids: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SnapBucket::VT_EDGE_CELL_IDS, edge_cell_ids);
  }
  #[inline]
  pub fn add_edge_indexes(&mut self, edge_indexes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SnapBucket::VT_EDGE_INDEXES, edge_indexes);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SnapBucketBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SnapBucketBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SnapBucket<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SnapBucket<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SnapBucket");
      ds.field("cell_id", &self.cell_id());
      ds.field("edge_cell_ids", &self.edge_cell_ids());
      ds.field("edge_indexes", &self.edge_indexes());
      ds.finish()
  }
}
pub enum SnapBucketsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SnapBuckets<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SnapBuckets<'a> {
  type Inner = SnapBuckets<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SnapBuckets<'a> {
  pub const VT_SNAP_BUCKETS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SnapBuckets { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SnapBucketsArgs<'args>
  ) -> flatbuffers::WIPOffset<SnapBuckets<'bldr>> {
    let mut builder = SnapBucketsBuilder::new(_fbb);
    if let Some(x) = args.snap_buckets { builder.add_snap_buckets(x); }
    builder.finish()
  }


  #[inline]
  pub fn snap_buckets(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SnapBucket<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SnapBucket>>>>(SnapBuckets::VT_SNAP_BUCKETS, None)}
  }
}

impl flatbuffers::Verifiable for SnapBuckets<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<SnapBucket>>>>("snap_buckets", Self::VT_SNAP_BUCKETS, false)?
     .finish();
    Ok(())
  }
}
pub struct SnapBucketsArgs<'a> {
    pub snap_buckets: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SnapBucket<'a>>>>>,
}
impl<'a> Default for SnapBucketsArgs<'a> {
  #[inline]
  fn default() -> Self {
    SnapBucketsArgs {
      snap_buckets: None,
    }
  }
}

pub struct SnapBucketsBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SnapBucketsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_snap_buckets(&mut self, snap_buckets: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<SnapBucket<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SnapBuckets::VT_SNAP_BUCKETS, snap_buckets);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SnapBucketsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SnapBucketsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SnapBuckets<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SnapBuckets<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SnapBuckets");
      ds.field("snap_buckets", &self.snap_buckets());
      ds.finish()
  }
}
}  // pub mod tobmapsnap

