[package]
name = "graphbuild"
version = "0.0.0"
edition = "2024"

[dependencies]
flatbuffers = "25.2.10"
s2 = "*"
schema = { path = "../schema" }
osmpbfreader = "*"
rayon = "*"
anyhow = "*"
thiserror = "*"
geo = "*"
log = "*"
env_logger = "*"