[package]
name = "snapbuild"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "25.2.10"
structopt = "0.3.26"
s2 = "*"
schema = { path = "../schema" }

[lib]
name = "snapbuild"
path = "src/lib.rs"

[[bin]]
name = "snapbuild"
path = "src/main.rs"
